### ISSUE TITLE
wrong text for ZoomOutAction.qml

### ISSUE THREAD

**Issue by RunningLight** [strahlex/QtQuickVcp#29]
(Still tracing out how all this stuff fits together!)

Accidentally discovered while playing with Cetus that in `QtQuickVcp/src/pathview/ZoomOutAction.qml`, lines 34/35 are

```
    text: qsTr("Zoom In")
    tooltip: qsTr("Zoom In")
```

Should be "Zoom Out" in both lines.

**Comment by strahlex** [comment]
Thanks. Fix: https://github.com/strahlex/QtQuickVcp/commit/a79dd4e7ddab43a305b2c92f7ced0ab49aeece5d
