### ISSUE TITLE
Android App - Machinekit Instances: + click does not work

### ISSUE THREAD

**Issue by koppi** [strahlex/QtQuickVcp#32]
On my Nexus 4, clicking on the "+" sign does not work:
![screen-nexus4](https://cloud.githubusercontent.com/assets/9458631/7335058/7b13b412-eba6-11e4-80f3-bd42d9d3a06d.png)

**Comment by strahlex** [comment]
With Android 5.0 right?

**Comment by koppi** [comment]
yes

**Comment by koppi** [comment]
Clicking on the '+' sign works now with the latest version.
