### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by hekav** [strahlex/QtQuickVcp#46]
Hello

on your VirtualBox image from here https://github.com/strahlex/MachinekitSDK/wiki/Getting-Started-with-the-Machinekit-SDK#using-the-machinetalk-preview-virtualbox-image I tried to install the latest Version.

First I tried to pull the latest Version, but I got conflicts. Then I saved the existing QtQuickVcp directory and entered the following commands:

`QMAKE=~/bin/Qt/5.*/gcc*/bin/qmake
QT_INSTALL_PREFIX=~/bin/Qt/5.*/gcc*

cd ~/bin

git clone https://github.com/strahlex/QtQuickVcp
mkdir -p build/QtQuickVcp
cd build/QtQuickVcp

$QMAKE ../../QtQuickVcp
make 
make docs
make install
make install_docs`

The make runs with no errors !
make install brings the following errors:

`machinekit@debian:~/bin/build/QtQuickVcp$ make install
cd 3rdparty/ && ( test -e Makefile || /home/machinekit/bin/Qt/5.3/gcc_64/bin/qmake /home/machinekit/bin/QtQuickVcp/3rdparty/3rdparty.pro -o Makefile ) && make -f Makefile install
make[1]: Entering directory `/home/machinekit/bin/build/QtQuickVcp/3rdparty'
cd machinetalk-protobuf-qt/ && ( test -e Makefile || /home/machinekit/bin/Qt/5.3/gcc_64/bin/qmake /home/machinekit/bin/QtQuickVcp/3rdparty/machinetalk-protobuf-qt/machinetalk-protobuf-qt.pro -o Makefile ) && make -f Makefile install
make[2]: Entering directory `/home/machinekit/bin/build/QtQuickVcp/3rdparty/machinetalk-protobuf-qt'
install -m 755 -p "libmachinetalk-protobuf.so.1.0.0" "/home/machinekit/bin/Qt/5.3/gcc_64/lib/libmachinetalk-protobuf.so.1.0.0"
strip --strip-unneeded "/home/machinekit/bin/Qt/5.3/gcc_64/lib/libmachinetalk-protobuf.so.1.0.0"
ln -f -s "libmachinetalk-protobuf.so.1.0.0" "/home/machinekit/bin/Qt/5.3/gcc_64/lib/libmachinetalk-protobuf.so"
ln -f -s "libmachinetalk-protobuf.so.1.0.0" "/home/machinekit/bin/Qt/5.3/gcc_64/lib/libmachinetalk-protobuf.so.1"
ln -f -s "libmachinetalk-protobuf.so.1.0.0" "/home/machinekit/bin/Qt/5.3/gcc_64/lib/libmachinetalk-protobuf.so.1.0"
make[2]: Leaving directory `/home/machinekit/bin/build/QtQuickVcp/3rdparty/machinetalk-protobuf-qt'
make[1]: Leaving directory `/home/machinekit/bin/build/QtQuickVcp/3rdparty'
cd src/ && ( test -e Makefile || /home/machinekit/bin/Qt/5.3/gcc_64/bin/qmake /home/machinekit/bin/QtQuickVcp/src/src.pro -o Makefile ) && make -f Makefile install
make[1]: Entering directory `/home/machinekit/bin/build/QtQuickVcp/src'
cd halremote/ && ( test -e Makefile || /home/machinekit/bin/Qt/5.3/gcc_64/bin/qmake /home/machinekit/bin/QtQuickVcp/src/halremote/halremote.pro -o Makefile ) && make -f Makefile install
make[2]: Entering directory `/home/machinekit/bin/build/QtQuickVcp/src/halremote'
/home/machinekit/bin/Qt/5.3/gcc_64/bin/qmlplugindump -nonrelocatable Machinekit.HalRemote 1.0 /home/machinekit/bin/build/QtQuickVcp/src/halremote/../../imports/ > /home/machinekit/bin/build/QtQuickVcp/src/halremote/../../imports/Machinekit/HalRemote/plugins.qmltypes
QQmlComponent: Component is not ready
make[2]: *** [install_dumppluginqmltypes] Error 3
make[2]: Leaving directory `/home/machinekit/bin/build/QtQuickVcp/src/halremote'
make[1]: *** [sub-halremote-install_subtargets-ordered] Error 2
make[1]: Leaving directory `/home/machinekit/bin/build/QtQuickVcp/src'
make: *** [sub-src-install_subtargets-ordered] Error 2
machinekit@debian:~/bin/build/QtQuickVcp$ 
`

What I'm doing wrong ?

Regards
Helmut

**Comment by strahlex** [comment]
Very old image. Please try https://github.com/strahlex/machinekit-vagrant
