### ISSUE TITLE
Cetus and QtQuickVcp

### ISSUE THREAD

**Issue by hekav** [strahlex/QtQuickVcp#47]
Hello,

actually I have two problems:

1. I Have a working CanOpen DS402 application running on my BeagleBone. I configured Cetus on the BeagleBone. The machinekit client works perfect except the jog stepping mode.  I runs as long as I press the plus or minus button instead of moving for a certain distance.

2. I have created a HalApplication for my Ds402 led's an it works perfectly:
![controlds402](https://cloud.githubusercontent.com/assets/12659936/13174876/e1ce9aea-d706-11e5-8a83-cb738a115ce4.png)

**Comment by strahlex** [comment]
Wow, good to see that someone is using QtQuickVcp. I think accidentally broke the jog button code in the current master some time ago (have the same problem in Machineface). I will try to fix this problem next week to get the current MachinekitClient client working correctly again.

**Comment by strahlex** [comment]
The jog problem should be fixed now.

**Comment by strahlex** [comment]
@hekav Can you please verify that the problem has been fixed.

**Comment by hekav** [comment]
Sorry I didn't know you want a response.

Yes it works perfectly. Thanks for the Update.
